### ISSUE TITLE
crosscat misappropriates entropy from numpy

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/crosscat#56] opened 2015-09-24 17:08 UTC
`simple_predictive_sample_unobserved` calls `numpy.random.multinomial` with no specified seed, so numpy presumably draws it from the environment.

**Comment by fsaad** [comment] 2015-09-24 18:36
This is probably an issue, but notice that `simple_predictive_sample` when invoked through `simple_predictive_sample_multistate`, __does__ have the numpy seed managed
https://github.com/probcomp/crosscat/blob/master/crosscat/utils/sample_utils.py#L257
The problem is when we invoke `simple_predictive_sample` externally -- which only happens when the 
crosscat instance has 1 model (which is rarely the case, and why I think the effects of the bug have not been witnessed).

**Comment by riastradh-probcomp** [comment] 2015-09-24 20:04
Unrelated.  That random state is correctly deterministically derived from the user-specified seed; the one ine `simple_predictive_sample_*unobserved*` is not.

**Comment by axch** [comment] 2015-11-02 21:30
Fixed by e5bab7ae94f368a73eb4d6ea24ed5cc88d0cc37b .

**Closed by axch** 2015-11-02 21:30 UTC
